### ISSUE TITLE
 I don't have access to pre-trained models stored in Google Drive

### ISSUE THREAD

**Issue by Kazuhito00** [Huage001/PaintTransformer#1]
Thank you for your wonderful work.

I didn't have access to [Google Drive](https://drive.google.com/file/d/1NDD54BLligyr8tzo8QGI5eihZisXK1nq/view?usp=sharing).
Will the Pretrained model be published later?
Or do you need a request for access?

**Comment by Huage001** [comment]
Thank you for your interest! The link is updated and you can try again.

**Comment by Kazuhito00** [comment]
Thank you for your quick response.
I was able to download it.
