### ISSUE TITLE
how is Stylized Painting generated?

### ISSUE THREAD

**Issue by qianyizhang** [Huage001/PaintTransformer#4]
hi,
great work! I am just wondering how is stylized painting generated? 
In the paper it was simply put "utilize existing style transfer methods", does it mean you first stylize the original picture to "stylized picture" then convert to painting with your work? or there is something to do with your stylized renderer?

If it is the former one, I suggest you put the stylized picture alongside with the final result to avoid any confusion.
If it is the latter one, can you share some more details?

Thanks,

**Comment by Huage001** [comment]
Hello,
Thank you for your interest and suggestion!
The former case is correct for this paper. Stylized painting is a minor extension of the main technique and we will consider your suggestion to make things clearer in the final version.
