### ISSUE TITLE
why grid need to divide 2 and add 0.25 

### ISSUE THREAD

**Issue by junedgar** [Huage001/PaintTransformer#8]
从代码上来看，grid表示归一化后的位置信息，范围是0-1
那么这里除以2 再加上0.25的操作怎么理解？
同时回归的宽高也除以2
https://github.com/Huage001/PaintTransformer/blob/7960b8eef2f6af7171af01933a3d8dbc73190a8d/inference/inference.py#L476
https://github.com/Huage001/PaintTransformer/blob/7960b8eef2f6af7171af01933a3d8dbc73190a8d/inference/inference.py#L477

**Comment by Huage001** [comment]
你好，
一幅图片的绘制基于patch完成，然而，直接对每个原始patch拼接，由于一些落在边缘的笔画会被直接裁剪掉，将会有非常明显的“接缝”，或是“棋盘”效果。因此，我们将每个原始大小为HxW的patch的实际绘图区域扩大到2Hx2W，使得在边缘的笔画也可以被完整地保留。

**Comment by junedgar** [comment]
> 你好， 一幅图片的绘制基于patch完成，然而，直接对每个原始patch拼接，由于一些落在边缘的笔画会被直接裁剪掉，将会有非常明显的“接缝”，或是“棋盘”效果。因此，我们将每个原始大小为HxW的patch的实际绘图区域扩大到2Hx2W，使得在边缘的笔画也可以被完整地保留。

感谢您的回复，思想我能理解，但是x,y的变换公式我还是有点不太理解
假设在没有做padding的时候，回归出来的(x0, y0) 为(0.1, 0.1)，归一化范围为0-1，那么padding的代码我看是上下左右各padding 25%，那么(x0', y0’)应该直接为（0.1 + 0.25， 0.1 + 0.25）, 那么按
https://github.com/Huage001/PaintTransformer/blob/7960b8eef2f6af7171af01933a3d8dbc73190a8d/inference/inference.py#L476
计算 （x0', y0'）为（0.1 / 2 + 0.25， 0.1/2 + 0.25 ）=(0.3, 0.3)
![image](https://user-images.githubusercontent.com/17995658/147750502-8e1ee3e1-825e-49a6-8bbf-407b9f3fcb5a.png)

这一行代码我看只padding了0.25
https://github.com/Huage001/PaintTransformer/blob/7960b8eef2f6af7171af01933a3d8dbc73190a8d/inference/inference.py#L121

**Comment by Huage001** [comment]
感谢您对代码细致的研究！
此处121行使用的patch_size_x和patch_size_y指的是扩大之后的patch，即原始边长x2。
因此“//4”表示上下左右各pad原始边长的50%。
而变换之前的坐标是相对于pad之前的原始patch而言的，在扩大之后尺度要缩小到原来的1/2，因此除以2。

**Comment by junedgar** [comment]
> 感谢您对代码细致的研究！ 此处121行使用的patch_size_x和patch_size_y指的是扩大之后的patch，即原始边长x2。 因此“//4”表示上下左右各pad原始边长的50%。 而变换之前的坐标是相对于pad之前的原始patch而言的，在扩大之后尺度要缩小到原来的1/2，因此除以2。

感谢细心解答，已琢磨清楚。

**Comment by Dreamer312** [comment]
你好，我没有太理解...........这个*0.5+0.25的操作

**Comment by Huage001** [comment]
> 你好，
> 一幅图片的绘制基于patch完成，然而，直接对每个原始patch拼接，由于一些落在边缘的笔画会被直接裁剪掉，将会有非常明显的“接缝”，或是“棋盘”效果。因此，我们将每个原始大小为HxW的patch的实际绘图区域扩大到2Hx2W，使得在边缘的笔画也可以被完整地保留。

这里的基本思路是扩大实际绘图区域，以免超出原来绘图面积的部分被裁剪掉。
