### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by Dreamer312** [Huage001/PaintTransformer#9]
old_param = torch.rand(self.opt.batch_size // 4, self.opt.used_strokes, self.d, device=self.device)

您好，感谢您的工作，关于在set input的时候，这个batch为什么要除以4，我没有太理解

**Comment by Huage001** [comment]
您好，
训练时模拟两个尺度的绘画过程，上一尺度（底图）的分辨率为64，预测尺度的分辨率为32，1个64x64的底图在训练时被划分为4个32x32的小块。更多细节可以参考论文的附录部分。

**Comment by Dreamer312** [comment]
也就是说，一个64*64的图片上画8笔，然后切分成四个32*32的patch，这8笔可能会被分割到四个不同的32*32patch上，作为背景，我的理解对嘛？
顺便我用你们的代码生成的图片质量并没有像展示的gif那样好，图片边缘有很多黑色点，这有可能是什么原因

**Comment by Dreamer312** [comment]
> 您好， 训练时模拟两个尺度的绘画过程，上一尺度（底图）的分辨率为64，预测尺度的分辨率为32，1个64x64的底图在训练时被划分为4个32x32的小块。更多细节可以参考论文的附录部分。

或者老哥，可以加个微信或者qq么，与其我让朋友把林天威的微信给我，我想了想直接找你比较好？

**Comment by Huage001** [comment]
> 也就是说，一个64_64的图片上画8笔，然后切分成四个32_32的patch，这8笔可能会被分割到四个不同的32*32patch上，作为背景，我的理解对嘛？ 顺便我用你们的代码生成的图片质量并没有像展示的gif那样好，图片边缘有很多黑色点，这有可能是什么原因

是的，这个理解很正确。

边缘黑色点说明有一些像素点没有被任何笔画覆盖到。在工程应用中，可以考虑先给图片做一定宽度的replicated padding，这一问题可以得到很大缓解。
